parameters:
  hshn_angular.asset.template_cache.class:                Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset
  hshn_angular.asset.template_cache.resource.class:       Hshn\AngularBundle\Assetic\TemplateCacheResource
  hshn_angular.asset.template_cache.naming.default.class: Hshn\AngularBundle\Naming\TemplateCacheNamingStrategy

services:
  hshn_angular.asset.template_cache:
    abstract: true
    class: %hshn_angular.asset.template_cache.class%
    arguments:
      - @hshn_angular.template_cache.template_finder
      - @hshn_angular.template_cache.compiler
      - ~

