parameters:
  hshn_angular.asset.template_cache.class:                Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset
  hshn_angular.asset.template_cache.resource.class:       Hshn\AngularBundle\Assetic\TemplateCacheResource
  hshn_angular.asset.template_cache.naming.default.class: Hshn\AngularBundle\Naming\TemplateCacheNamingStrategy

services:
  hshn_angular.asset.template_cache:
    abstract: true
    class: %hshn_angular.asset.template_cache.class%
    arguments:
      - @hshn_angular.template_cache.template_finder
      - @hshn_angular.template_cache.compiler
      - ~

  hshn_angular.asset.config_loader:
    public: false
    class: %assetic.config_loader.class%
    tags:
      - { name: assetic.formula_loader, alias: hshn_ng_template_cache }

  hshn_angular.asset.template_cache.resource:
    public: false
    class: %hshn_angular.asset.template_cache.resource.class%
    arguments:
      - @hshn_angular.template_cache.manager
      - @hshn_angular.asset.template_cache.naming
    tags:
      - { name: assetic.formula_resource, loader: hshn_ng_template_cache }

  hshn_angular.asset.template_cache.naming.default:
    class: %hshn_angular.asset.template_cache.naming.default.class%
