parameters:
  hshn_angular.asset.template_cache.class:                Hshn\AngularBundle\Assetic\Asset\TemplateCacheAsset

services:
  hshn_angular.asset.template_cache:
    abstract: true
    class: %hshn_angular.asset.template_cache.class%
    arguments:
      - "@hshn_angular.template_cache.template_finder"
      - "@hshn_angular.template_cache.compiler"
      - ~
